# Generated by Django 3.2.18 on 2023-03-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uaa', '0006_auto_20230318_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totalfile',
            field=models.IntegerField(default=0),
        ),
    ]
