# Generated by Django 3.2.18 on 2023-03-19 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loafum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('eloadingDate', models.DateField()),
                ('aloadingDate', models.DateField()),
                ('fumigationStartDate', models.DateField()),
                ('fumigationEndDate', models.DateField()),
                ('placeName', models.CharField(blank=True, max_length=100, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_loafum', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdAt', '-updatedAt'],
            },
        ),
        migrations.CreateModel(
            name='VesselBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('bookingDate', models.DateField()),
                ('eVesselName', models.CharField(blank=True, max_length=100, null=True)),
                ('aVesselName', models.CharField(blank=True, max_length=100, null=True)),
                ('carrierBookingRef', models.CharField(blank=True, max_length=100, null=True)),
                ('mbol', models.CharField(blank=True, max_length=100, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_vesselBooking', to=settings.AUTH_USER_MODEL)),
                ('updatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_vesselBookig', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdAt', '-updatedAt'],
            },
        ),
        migrations.CreateModel(
            name='Openf',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('itemNo', models.PositiveIntegerField(unique=True)),
                ('batchNo', models.PositiveIntegerField()),
                ('mopi', models.CharField(blank=True, max_length=30, null=True)),
                ('contqnty', models.PositiveIntegerField()),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('transferPoNo', models.PositiveIntegerField()),
                ('freightBookingNo', models.PositiveIntegerField()),
                ('carrierName', models.CharField(blank=True, max_length=100, null=True)),
                ('etd', models.DateField()),
                ('eta', models.DateField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_openf', to=settings.AUTH_USER_MODEL)),
                ('updatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_openff', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_opennf', to=settings.AUTH_USER_MODEL)),
                ('vesselBooking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vesselBooking_openf', to='reportdata.vesselbooking')),
            ],
            options={
                'ordering': ['-createdAt', '-updatedAt'],
            },
        ),
        migrations.CreateModel(
            name='loaVessel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('eportDeliveryDate', models.DateField()),
                ('aportDeliveryDate', models.DateField()),
                ('adateDeparture', models.DateField()),
                ('adateArrival', models.DateField()),
                ('siReceiveDate', models.DateField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_loavesel', to=settings.AUTH_USER_MODEL)),
                ('openf', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='openf_loavessel', to='reportdata.loafum')),
                ('updatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_loavessel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdAt', '-updatedAt'],
            },
        ),
        migrations.AddField(
            model_name='loafum',
            name='openf',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='openf_loafum', to='reportdata.openf'),
        ),
        migrations.AddField(
            model_name='loafum',
            name='updatedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_loafumm', to=settings.AUTH_USER_MODEL),
        ),
    ]
