# Generated by Django 3.2.18 on 2023-03-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loafum',
            name='aloadingDateNo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loafum',
            name='fumigationEndDateNo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loafum',
            name='fumigationStartDateNo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loavessel',
            name='adateArrivalNo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loavessel',
            name='adateDepartureNo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loavessel',
            name='aportDeliveryDateNo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loavessel',
            name='siReceiveDateNo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='openf',
            name='etaNo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='openf',
            name='etdNo',
            field=models.IntegerField(default=0),
        ),
    ]
