# Generated by Django 3.2.18 on 2023-03-19 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportdata', '0002_auto_20230319_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openf',
            name='etdNo',
        ),
    ]
