# Generated by Django 3.2.18 on 2023-03-20 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportdata', '0003_remove_openf_etdno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loavessel',
            old_name='aportDeliveryDate',
            new_name='portDeliveryDate',
        ),
        migrations.RemoveField(
            model_name='loafum',
            name='placeName',
        ),
        migrations.RemoveField(
            model_name='loavessel',
            name='eportDeliveryDate',
        ),
        migrations.RemoveField(
            model_name='loavessel',
            name='openf',
        ),
        migrations.AddField(
            model_name='loavessel',
            name='loafum',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loafm_loavessel', to='reportdata.loafum'),
        ),
    ]
