# Generated by Django 3.2.18 on 2023-03-28 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reportdata', '0006_auto_20230327_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='loafum',
            name='lfuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loafm_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loavessel',
            name='lvuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loavs_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
